const THEMES = [
    {
        "name": "我的企业模版 (Enterprise)",
        "key": "my-enterprise",
        "description": "基于 '智能论文助手' 的定制化企业风格。支持 Grid 布局、卡片、Checklist。",
        "prompt": "Role: Professional UI/UX Designer for Enterprise Presentations.\nTarget: Reveal.js HTML slides.\n\nDesign System (MUST USE):\n- WRAPPER: <div class='custom-slide'>...</div>\n- LAYOUTS: Use <div class='grid-2'> or <div class='grid-3'>. Do NOT stack.\n- CARDS: <div class='card'><h3>Title</h3><p>Content</p></div>\n- TAGS: <span class='tag'>Keyword</span>\n- CHECKLIST: <div class='checklist-item'>...</div>\n\nTask:\nConvert content to this structure. Make it look professional and clean.",
        "css": ":root { --bg-color: #f7f8fa; --card-bg: #ffffff; --primary: #2563eb; --primary-light: #eff6ff; --text-main: #1e293b; --text-sub: #64748b; --text-accent: #3b82f6; --border: #e2e8f0; --shadow: 0 10px 30px -10px rgba(0,0,0,0.08); --radius: 16px; } body, .reveal { background-color: var(--bg-color) !important; color: var(--text-main); font-family: -apple-system, sans-serif; } .reveal .slides section { padding: 0; height: 100%; text-align: left; } .custom-slide { width: 100%; height: 100%; padding: 40px 60px; box-sizing: border-box; display: flex; flex-direction: column; font-size: 28px; } .header { margin-bottom: 30px; text-align: center; } .header.left { text-align: left; border-left: 6px solid var(--primary); padding-left: 20px; } .header h1 { font-size: 1.6em; font-weight: 800; color: var(--text-main); margin: 0 0 10px 0; text-transform: none; } .en-subtitle { font-size: 0.5em; color: var(--text-accent); font-weight: 700; letter-spacing: 2px; text-transform: uppercase; display: block; } .content { flex: 1; display: flex; flex-direction: column; gap: 20px; } .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 40px; } .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 30px; } .card { background: var(--card-bg); border-radius: var(--radius); padding: 30px; box-shadow: var(--shadow); border: 1px solid rgba(255,255,255,0.5); } .card h3 { font-size: 1.1em; color: var(--text-main); font-weight: 700; margin-bottom: 10px; } .card p { font-size: 0.8em; color: var(--text-sub); line-height: 1.5; margin: 0; } .tag { display: inline-block; background: var(--primary-light); color: var(--primary); padding: 5px 15px; border-radius: 20px; font-size: 0.6em; font-weight: 600; margin: 5px 5px 0 0; } .checklist-item { background: white; padding: 15px; border-radius: 12px; border: 1px solid var(--border); display: flex; align-items: center; gap: 15px; font-size: 0.8em; margin-bottom: 10px; } .check-box { width: 24px; height: 24px; border: 2px solid var(--primary); border-radius: 6px; display: flex; align-items: center; justify-content: center; } .check-box::after { content: '✓'; color: var(--primary); font-weight: bold; }"
    },
    {
        "name": "严谨学术风 (Academic)",
        "key": "academic-style",
        "description": "模拟 LaTeX 排版，衬线字体，纸质背景，适合论文答辩。",
        "prompt": "Role: Academic Presentation Specialist.\nTarget: Reveal.js HTML slides (LaTeX Style).\n\nDesign System (MUST USE):\n- WRAPPER: <div class='custom-slide'>...</div>\n- CARD as BOX: <div class='card'> becomes a Theorem/Definition box.\n- HEADER: <div class='header'>...</div>\n- LISTS: Use numbered lists or bullet points heavily.\n\nTask:\nStructure content logically. Make it look rigorous, printed, and clean. Use serif fonts.",
        "css": ":root { --bg-color: #fdfdfd; --text-main: #2a2a2a; --primary: #800000; --secondary: #003366; --border: #333; --card-bg: #f9f9f9; } body, .reveal { background-color: var(--bg-color) !important; color: var(--text-main); font-family: 'Times New Roman', Times, serif; } .reveal .slides section { padding: 0; height: 100%; text-align: left; } .custom-slide { padding: 50px; height: 100%; display: flex; flex-direction: column; box-sizing: border-box; font-size: 30px; border: 1px solid #eee; box-shadow: 0 0 20px rgba(0,0,0,0.05) inset; } .header { border-bottom: 2px solid var(--text-main); padding-bottom: 15px; margin-bottom: 30px; text-align: center; } .header.left { text-align: left; } .header h1, .header h2 { font-family: 'Times New Roman', serif; color: var(--primary); font-weight: bold; margin: 0; text-transform: uppercase; letter-spacing: 1px; font-size: 1.4em; } .en-subtitle { font-family: 'Helvetica', sans-serif; font-size: 0.5em; color: #666; margin-top: 5px; display: block; font-style: italic; } .content { flex: 1; display: flex; flex-direction: column; gap: 20px; } .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 50px; padding: 20px 0; border-top: 1px dashed #ccc; border-bottom: 1px dashed #ccc; } .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 30px; } .card { background: var(--card-bg); border: 1px solid var(--text-main); padding: 20px; box-shadow: 3px 3px 0px rgba(0,0,0,0.1); position: relative; } .card::before { content: 'Figure / Box'; position: absolute; top: -10px; left: 10px; background: var(--bg-color); padding: 0 5px; font-size: 0.5em; font-weight: bold; color: var(--secondary); border: 1px solid var(--text-main); } .card h3 { font-size: 1em; color: var(--secondary); margin: 0 0 10px 0; font-weight: bold; text-decoration: underline; } .card p { font-size: 0.8em; line-height: 1.6; margin: 0; text-align: justify; } .tag { display: inline-block; border: 1px solid var(--secondary); color: var(--secondary); padding: 2px 8px; font-size: 0.6em; margin-right: 5px; font-family: 'Courier New', monospace; background: #eef; } .checklist-item { margin-bottom: 10px; padding-left: 20px; border-left: 3px solid var(--primary); font-style: italic; background: #fff5f5; padding: 10px; }"
    },
    {
        "name": "前沿科研风 (Scientific)",
        "key": "scientific-research",
        "description": "高精尖实验室风格，网格背景，数据可视化导向，冷冷静。",
        "prompt": "Role: Scientific Researcher Presentation.\nDesign System:\n- WRAPPER: <div class='custom-slide'>...</div>\n- CARD: Use <div class='card'> for data panels.\n- HEADER: <div class='header'> with project codes.\n- GRID: Strict alignment.\n\nTask:\nVisualize steps clearly. Use a clean, sterile, high-precision aesthetic (Helvetica/Arial).",
        "css": ":root { --bg-color: #ffffff; --text-main: #111; --primary: #0056b3; --accent: #00d2ff; --gray: #f0f0f0; } body, .reveal { background-color: var(--bg-color) !important; color: var(--text-main); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-image: linear-gradient(#e5e5e5 1px, transparent 1px), linear-gradient(90deg, #e5e5e5 1px, transparent 1px); background-size: 40px 40px; } .reveal .slides section { padding: 0; height: 100%; text-align: left; } .custom-slide { padding: 40px; height: 100%; display: flex; flex-direction: column; box-sizing: border-box; background: rgba(255,255,255,0.9); backdrop-filter: blur(2px); border: 1px solid #ccc; margin: 10px; } .header { display: flex; align-items: baseline; justify-content: space-between; border-bottom: 4px solid var(--primary); padding-bottom: 10px; margin-bottom: 20px; } .header h1, .header h2 { font-weight: 900; letter-spacing: -1px; margin: 0; color: var(--text-main); font-size: 2em; } .en-subtitle { font-family: 'Roboto Mono', monospace; color: var(--primary); font-size: 0.7em; background: #eef6ff; padding: 4px 8px; } .header.left { flex-direction: row; } .content { flex: 1; display: flex; flex-direction: column; gap: 20px; } .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; } .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; } .card { background: #fff; border: 1px solid #ddd; padding: 20px; position: relative; overflow: hidden; } .card::after { content: ''; position: absolute; top: 0; left: 0; width: 4px; height: 100%; background: var(--accent); } .card h3 { font-family: 'Roboto Mono', monospace; font-size: 0.9em; color: #666; text-transform: uppercase; margin-bottom: 15px; letter-spacing: 1px; } .card p { font-size: 1.2em; font-weight: 500; color: var(--primary); margin: 0; } .tag { font-family: 'Roboto Mono', monospace; font-size: 0.6em; border: 1px solid var(--text-main); padding: 2px 6px; margin-right: 5px; color: var(--text-main); background: transparent; } .checklist-item { display: flex; align-items: center; gap: 10px; border-bottom: 1px solid #eee; padding: 10px 0; } .check-box { width: 16px; height: 16px; background: var(--primary); }"
    },
    {
        "name": "高端商业风 (Commercial)",
        "key": "premium-commercial",
        "description": "黑金配色，发布会风格。极致简约，强调视觉冲击力。",
        "prompt": "Role: Keynote Speaker Designer (Apple/Ted Style).\nDesign System:\n- WRAPPER: <div class='custom-slide'>...</div>\n- CARD: Minimalist dark cards <div class='card'>\n- HEADER: Big bold headers.\n- TAGS: Gradient pills.\n\nTask:\nUse high contrast. Dark mode. Focus on IMPACT. Minimal text.",
        "css": ":root { --bg-color: #000000; --text-main: #ffffff; --text-sub: #888888; --accent: #D4AF37; --card-bg: #111111; } body, .reveal { background-color: var(--bg-color) !important; color: var(--text-main); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; } .reveal .slides section { padding: 0; height: 100%; text-align: center; } .custom-slide { padding: 60px; height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; box-sizing: border-box; } .header { margin-bottom: 60px; max-width: 800px; } .header.left { text-align: center; border: none; padding: 0; } /* Force center for commercial look */ .header h1, .header h2 { font-size: 2.5em; font-weight: 700; background: linear-gradient(135deg, #fff 0%, #888 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin: 0 0 20px 0; letter-spacing: -1px; } .en-subtitle { color: var(--accent); font-size: 0.6em; letter-spacing: 3px; text-transform: uppercase; font-weight: 600; } .content { width: 100%; display: flex; flex-direction: column; align-items: center; gap: 40px; } .grid-2, .grid-3 { display: grid; gap: 40px; width: 100%; max-width: 1000px; } .grid-2 { grid-template-columns: 1fr 1fr; } .grid-3 { grid-template-columns: 1fr 1fr 1fr; } .card { background: var(--card-bg); border-radius: 20px; padding: 40px; text-align: left; border: 1px solid #333; transition: transform 0.3s ease; } .card:hover { transform: translateY(-5px); border-color: var(--accent); } .card h3 { color: var(--accent); font-size: 1.2em; margin-bottom: 15px; font-weight: 500; } .card p { color: var(--text-sub); font-size: 0.9em; line-height: 1.6; } .tag { background: linear-gradient(90deg, #D4AF37, #FDC830); color: #000; padding: 6px 16px; border-radius: 50px; font-size: 0.7em; font-weight: bold; border: none; display: inline-block; margin: 5px; box-shadow: 0 4px 15px rgba(212, 175, 55, 0.3); } .checklist-item { border: 1px solid #333; padding: 20px; border-radius: 12px; width: 100%; max-width: 600px; display: flex; justify-content: space-between; align-items: center; background: #0a0a0a; } .check-box { visibility: hidden; }"
    }
];
